# Generated by Django 4.1.7 on 2023-02-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choices',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_grade',
        ),
        migrations.AddField(
            model_name='question',
            name='grade',
            field=models.IntegerField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
