# Generated by Django 4.1.7 on 2023-02-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_question_course_alter_question_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='total_enrollment',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.IntegerField(default=1),
        ),
    ]
