# Generated by Django 4.1.7 on 2023-02-18 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0005_alter_course_total_enrollment_alter_lesson_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.IntegerField(default=1),
        ),
    ]
