# Generated by Django 4.1.7 on 2023-02-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0006_alter_question_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='lesson',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(default='question text', max_length=300),
        ),
    ]
